# TODO Espiiii, 2021-03-18:
main: me.espiiii.test.spigot.pluginTest.Main

name: PluginTest

description: Plugin dedie au test

author: Espiiiii

version: 1.0.0

commands:
   kit:
      description: Your description
      usage: /<command>
      permission: PluginTest.doCommandKit
   welcome:
      description: dire bonjour a
      usage: /<command>
      permission: PluginTest.doCommandHello
   gm:
      desctiption: Gamemode Changer
      usage: /<command>
      permission: PluginTest.doCommandGm
